packages:
  - packages/*
  - apps/*
  - qa/**

catalog:
  '@strapi/strapi': 5.48.1
  '@tailwindcss/postcss': ^4.3.1
  '@types/node': ^24.13.2
  class-variance-authority: ^0.7.1
  eslint-plugin-jsx-a11y: ^6.10.2
  lodash: ^4.18.1
  postcss: ^8.5.15
  qs: ^6.15.2
  tailwindcss: ^4.3.1
  typescript: ^5.9.3
  vitest: ~4.1.9
